name: Data Mining Blog
markdown: redcarpet
highlighter: pygments
#Comment out url when working locally to resolve base urls correctly
#url: http://dehnx058.github.io/
paginate: 8
#description:     Jekyll theme for Programmers
#intro: White Paper is a Jekyll theme most suited to be used on tech blogs that like their content to shine.
logo:             logo.png
disqus_shortname:

# Owner/author information
owner:
  name:           Greyson Dehn
  avatar:         /assets/images/author.jpg
  email:          dehnx058@umn.edu
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  github:		  https://github.com/dehnx058
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true